version: '3.8'

services:
  service-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
    networks:
      - mysql-network    

  service-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: service-mysql
      PMA_PORT: 3306
    ports:
      - "80:80"
    networks:
      - mysql-network
    depends_on:
      - service-mysql

networks:
  mysql-network:
    driver: bridge
